services:
  backend:
    build: ./backend
    image: client/backend:1.0.0
    container_name: fastapi-backend
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8000:8000"

  # frontend:
  #   build: ./frontend
  #   image: client/frontend:1.0.0
  #   container_name: react-frontend
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true